spring:
  mvc:
    date-format: yyyy-MM-dd

  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456

mybatis:
  type-aliases-package: com.jiawei.springboot03web.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml